 databases_configs:
    mysql:
        connection:
            host: host.com
            user: user
            passwd: pass
            db: database
            port: 3306
        queries:
            query_1: " "
            query_2:
            query_3:
            query_4:
    ssql:
        connection:
            host: host.com
            user: user
            passwd: passwd
            db: db
            port: 3306
            as_dict: Ture
            login_timeout : 20
        queries:
            query_1:
            query_2:
            query_3:
            query_4:

